<template>
    <div class="list">
        <ul>
            <li>新闻列表1</li>
            <li>新闻列表2</li>
            <li>新闻列表3</li>
            <li>新闻列表4</li>
            <li>新闻列表5</li>
            <li>新闻列表6</li>
            <li>新闻列表7</li>
            <li>新闻列表8</li>
            <li>新闻列表9</li>
            <li>新闻列表10</li>
            <li>新闻列表11</li>
            <li>新闻列表12</li>
            <li>新闻列表13</li>
            <li>新闻列表14</li>
            <li>新闻列表15</li>
            <li>新闻列表16</li>
            <li>新闻列表17</li>
            <li>新闻列表18</li>
            <li>新闻列表19</li>
            <li>新闻列表20</li>
            <li>新闻列表21</li>
            <li>新闻列表22</li>
            <li>新闻列表23</li>
            <li>新闻列表24</li>
            <li>新闻列表25</li>
            <li>新闻列表26</li>
            <li>新闻列表27</li>
            <li>新闻列表28</li>
            <li>新闻列表29</li>
            <li>新闻列表30</li>
            <li>新闻列表31</li>
            <li>新闻列表32</li>
            <li>新闻列表33</li>
            <li>新闻列表34</li>
            <li>新闻列表35</li>
            <li>新闻列表36</li>
            <li>新闻列表37</li>
            <li>新闻列表38</li>
            <li>新闻列表39</li>
            <li>新闻列表40</li>
            <li>新闻列表41</li>
            <li>新闻列表42</li>
            <li>新闻列表43</li>
            <li>新闻列表44</li>
            <li>新闻列表45</li>
            <li>新闻列表46</li>
            <li>新闻列表47</li>
            <li>新闻列表48</li>
            <li>新闻列表49</li>
            <li>新闻列表50</li>
            <li>新闻列表51</li>
            <li>新闻列表52</li>
            <li>新闻列表53</li>
            <li>新闻列表54</li>
            <li>新闻列表55</li>
            <li>新闻列表56</li>
            <li>新闻列表57</li>
            <li>新闻列表58</li>
            <li>新闻列表59</li>
            <li>新闻列表60</li>
            <li>新闻列表61</li>
            <li>新闻列表62</li>
            <li>新闻列表63</li>
            <li>新闻列表64</li>
            <li>新闻列表65</li>
            <li>新闻列表66</li>
            <li>新闻列表67</li>
            <li>新闻列表68</li>
            <li>新闻列表69</li>
            <li>新闻列表70</li>
            <li>新闻列表71</li>
            <li>新闻列表72</li>
            <li>新闻列表73</li>
            <li>新闻列表74</li>
            <li>新闻列表75</li>
            <li>新闻列表76</li>
            <li>新闻列表77</li>
            <li>新闻列表78</li>
            <li>新闻列表79</li>
            <li>新闻列表80</li>
            <li>新闻列表81</li>
            <li>新闻列表82</li>
            <li>新闻列表83</li>
            <li>新闻列表84</li>
            <li>新闻列表85</li>
            <li>新闻列表86</li>
            <li>新闻列表87</li>
            <li>新闻列表88</li>
            <li>新闻列表89</li>
            <li>新闻列表90</li>
            <li>新闻列表91</li>
            <li>新闻列表92</li>
            <li>新闻列表93</li>
            <li>新闻列表94</li>
            <li>新闻列表95</li>
            <li>新闻列表96</li>
            <li>新闻列表97</li>
            <li>新闻列表98</li>
            <li>新闻列表99</li>
            <li>新闻列表100</li>
        </ul>
    </div>
</template>

<script>
export default {
    
    data(){
        return{

        }
    }
}
</script>

<style>
    /* .list{
        height: 300px;
        overflow: scroll;
    } */
</style>